### ISSUE TITLE
privateKey

### ISSUE THREAD

**Issue by rhatami7495** [Enes-Kayiklik/Wallet-Connect-Example#1]
Hi.how to get privateKey?

**Comment by Enes-Kayiklik** [comment]
Hello. Thank you for your attention to this repo @rhatami7495. If you want to get private key using WalletConnect this is not possible because of the security things. If you are not asking for this can you please be more specific?

**Comment by rhatami7495** [comment]
Thank you.
but I want to connected my wallet from my app to wallet connect for example when I used https://app.sushi.com/ and pressed connect to wallet and scan qrcode on my app, get (wc:1f6e47c3-866a-4f42-ad74-158ea73e568b@1?bridge=https%3A%2F%2Fp.bridge.walletconnect.org&key=309cbc52888f1aa12c68a5aa25a75694250e1b8b16c20fa9a92791d5a7f8f2e5) link,after, how to connect this link from my app?
I want using to your libarary,but used private key.

**Comment by Enes-Kayiklik** [comment]
Maybe [this](https://docs.walletconnect.com/mobile-linking) can help you

**Comment by rhatami7495** [comment]
Thank you.
